// Export as plug-in (DIY closed loop): Customize content in the session - special effects/transitions generated by submit_shader,
// MG clips on timeline - packaged as openchatcut-plugin@1 JSON. Pure function, data is injected by the caller
// (The browser UI is in library/PluginExport.tsx), the product must pass validatePack before it can be downloaded.
import { PLUGIN_FORMAT, type PluginItem, type PluginNumberProp, type PluginPack } from './types';
import { validatePack } from './validate';
import type { FxProperty, SerializableFxDef } from '../gl/fx/uniforms';
import type { CustomTransitionDef } from '../gl/customTransitions';
import type { TimelineItem, TransitionItem } from '../editor/types';

/** A checkable export candidate(item.id by buildExportPack unified rearrangement,Take a seat here first) */
export interface ExportCandidate {
  /** Unique key within session(Used for checked status) */
  key: string;
  label: string;
  item: PluginItem;
}

function numberProps(props: FxProperty[] | undefined): PluginNumberProp[] | undefined {
  if (!props?.length) return undefined;
  const out = props
    .filter((p) => p.kind !== 'color')
    .map((p) => ({ key: p.key, label: p.label, default: p.default as number, min: (p as { min: number }).min, max: (p as { max: number }).max, ...(p.step ? { step: p.step } : {}) }));
  return out.length ? out : undefined;
}

/** Custom effects candidates:Only accept custom:(submit_shader product);plugin:(Others' content)with builtin: Not to guide */
export function fxCandidates(defs: SerializableFxDef[]): ExportCandidate[] {
  const seen = new Set<string>();
  const out: ExportCandidate[] = [];
  for (const d of defs) {
    if (!d.id.startsWith('custom:') || d.cube || seen.has(d.id)) continue;
    seen.add(d.id);
    out.push({
      key: d.id,
      label: d.name,
      item: {
        type: 'fx', id: 'fx', name: d.name,
        ...(d.desc ? { desc: d.desc.slice(0, 500) } : {}),
        frag: d.frag,
        ...(numberProps(d.props) ? { props: numberProps(d.props) } : {}),
        ...(d.passes ? { passes: d.passes } : {}),
      },
    });
  }
  return out;
}

/** Custom transition candidates:in the registry custom:tr-*,Plus the only remaining ones on the timeline customFrag of
 * (submit_shader Clear the registry after refreshing,frag only live in TransitionItem on). press frag Remove weight. */
export function transitionCandidates(defs: CustomTransitionDef[], transitions: TransitionItem[]): ExportCandidate[] {
  const seenFrag = new Set<string>();
  const out: ExportCandidate[] = [];
  for (const d of defs) {
    if (!d.id.startsWith('custom:') || seenFrag.has(d.frag)) continue;
    seenFrag.add(d.frag);
    out.push({
      key: d.id,
      label: d.label,
      item: {
        type: 'transition', id: 'tr', name: d.label, frag: d.frag,
        ...(d.props.length ? { props: d.props.map((p) => ({ key: p.key, label: p.label, default: p.default, min: p.min, max: p.max, ...(p.step ? { step: p.step } : {}) })) } : {}),
      },
    });
  }
  for (const t of transitions) {
    if (t.type !== 'custom-shader' || !t.customFrag || seenFrag.has(t.customFrag)) continue;
    seenFrag.add(t.customFrag);
    const name = t.customLabel ?? 'Custom transition';
    // Only uniform values, infer the conservative range of adjustable properties
    const props: PluginNumberProp[] = Object.entries(t.customUniforms ?? {}).map(([k, v]) => ({
      key: k.replace(/^u_/, ''),
      label: k.replace(/^u_/, ''),
      default: v,
      min: Math.min(0, v),
      max: v === 0 ? 1 : Math.max(1, Math.abs(v) * 2),
    }));
    out.push({
      key: `timeline:${t.id}`,
      label: name,
      item: { type: 'transition', id: 'tr', name, frag: t.customFrag, ...(props.length ? { props } : {}) },
    });
  }
  return out;
}

/** timeline MG candidate(press code Remove duplicates,The same template is tracked multiple times and only one output appears.) */
export function mgCandidates(items: TimelineItem[]): ExportCandidate[] {
  const seenCode = new Set<string>();
  const out: ExportCandidate[] = [];
  for (const it of items) {
    if (it.kind !== 'motion-graphic' || !it.code || seenCode.has(it.code)) continue;
    seenCode.add(it.code);
    out.push({
      key: `mg:${it.id}`,
      label: it.name,
      item: {
        type: 'mg-template', id: 'mg', name: it.name, code: it.code,
        ...(it.width ? { width: it.width } : {}),
        ...(it.height ? { height: it.height } : {}),
        ...(it.props && Object.keys(it.props).length ? { props: it.props } : {}),
      },
    });
  }
  return out;
}

export interface ExportMeta {
  id: string;
  name: string;
  version?: string;
  author?: string;
  description?: string;
}

export type BuildResult = { ok: true; pack: PluginPack; json: string } | { ok: false; errors: string[] };

/** group package:Each type of content is rearranged uniquely id(fx-1/tr-1/mg-1…),Whole package validatePack Only then was it released. */
export function buildExportPack(meta: ExportMeta, selected: PluginItem[]): BuildResult {
  const counters: Record<string, number> = {};
  const items = selected.map((item) => {
    const prefix = item.type === 'mg-template' ? 'mg' : item.type === 'transition' ? 'tr' : item.type;
    counters[prefix] = (counters[prefix] ?? 0) + 1;
    return { ...item, id: `${prefix}-${counters[prefix]}` };
  });
  const pack = {
    format: PLUGIN_FORMAT,
    id: meta.id.trim(),
    name: meta.name.trim(),
    version: meta.version?.trim() || '1.0.0',
    ...(meta.author?.trim() ? { author: meta.author.trim() } : {}),
    ...(meta.description?.trim() ? { description: meta.description.trim() } : {}),
    items,
  };
  const res = validatePack(pack);
  if (!res.ok) return { ok: false, errors: res.errors };
  return { ok: true, pack: res.pack, json: JSON.stringify(res.pack, null, 2) };
}
