import { useEffect, useState } from 'react';

// Timeline clip previews: waveform peaks and video thumbnail strips. The server generates and caches
// /api/waveform and /api/filmstrip (see server/plugins/media-preview.ts); this module only handles
// src-based deduplication, in-process caching, and subscriptions, so N cuts of one asset issue one request.
// Waveforms and frame strips are generated by local ffmpeg, and the client is responsible for time mapping.

export interface ClipPreview {
  /** 0..1 amplitude envelope, peaksPerSecond per second; no audio track is an empty array */
  peaks: number[];
  peaksPerSecond: number;
  /** The real duration of the source file (not the duration after clipping) */
  durationMs: number;
  /** Video frame bar URL (video only; not ready/null on failure) */
  stripUrl: string | null;
}

type Entry = { value: ClipPreview | null; promise: Promise<void> | null; listeners: Set<() => void> };

const entries = new Map<string, Entry>();

/** Only local assets can be previewed (blob:/remote URL server cannot reach) */
export function isPreviewable(src: string | undefined): src is string {
  return !!src && src.startsWith('/media/uploads/');
}

function entryFor(key: string): Entry {
  let e = entries.get(key);
  if (!e) {
    e = { value: null, promise: null, listeners: new Set() };
    entries.set(key, e);
  }
  return e;
}

async function load(src: string, wantStrip: boolean, e: Entry): Promise<void> {
  const q = `src=${encodeURIComponent(src)}`;
  const wave = await fetch(`/api/waveform?${q}`)
    .then((r) => (r.ok ? r.json() as Promise<{ peaks?: number[]; peaksPerSecond?: number; durationMs?: number }> : null))
    .catch(() => null);
  // The frame bar only checks the availability once: if successful, the URL is handed over to the CSS background (the browser caches the bytes itself)
  const stripUrl = wantStrip
    ? await fetch(`/api/filmstrip?${q}`).then((r) => (r.ok ? `/api/filmstrip?${q}` : null)).catch(() => null)
    : null;
  e.value = {
    peaks: wave?.peaks ?? [],
    peaksPerSecond: wave?.peaksPerSecond ?? 100,
    durationMs: wave?.durationMs ?? 0,
    stripUrl,
  };
  for (const fn of e.listeners) fn();
}

/**
 * Fragment preview data. Multiple fragments of the same src share one request and one result.
 * kind determines whether frame strips are required (video only); non-native assets directly return null.
 */
export function useClipPreview(src: string | undefined, kind: string): ClipPreview | null {
  const key = isPreviewable(src) ? src : '';
  const wantStrip = kind === 'video';
  const [, bump] = useState(0);

  useEffect(() => {
    if (!key) return;
    const e = entryFor(key);
    const onChange = () => bump((n) => n + 1);
    e.listeners.add(onChange);
    if (!e.value && !e.promise) {
      e.promise = load(key, wantStrip, e).finally(() => { e.promise = null; });
    }
    return () => { e.listeners.delete(onChange); };
  }, [key, wantStrip]);

  return key ? entryFor(key).value : null;
}

/**
 * Geometry mapping within fragments:
 * The clip's left edge is aligned to the source frame srcIn, and each timeline pixel is advanced by playbackRate/px of the source frame.
 * The entire frame bar covers [0, source duration), so CSS background horizontal size = source frame number × px / rate,
 * Lateral displacement = -srcIn × px / rate.
 */
export function filmstripBackground(
  preview: ClipPreview,
  { px, fps, srcInFrame, playbackRate }: { px: number; fps: number; srcInFrame: number; playbackRate: number },
): { backgroundImage: string; backgroundSize: string; backgroundPositionX: string } | null {
  if (!preview.stripUrl || !preview.durationMs) return null;
  const rate = playbackRate > 0 ? playbackRate : 1;
  const srcFrames = (preview.durationMs / 1000) * fps;
  const fullW = (srcFrames * px) / rate;
  if (!(fullW > 0)) return null;
  return {
    backgroundImage: `url(${preview.stripUrl})`,
    backgroundSize: `${fullW.toFixed(1)}px 100%`,
    backgroundPositionX: `${(-(srcInFrame * px) / rate).toFixed(1)}px`,
  };
}

/**
 * The sonic path within the clip's visible window (same mapping as the frame strip). Returns the SVG path; returns an empty string without peaks.
 * The vertical coordinate is symmetrical with height/2 as the axis, and x takes the largest peak value covered by the column column by pixel (to avoid sampling flicker).
 */
export function peaksPath(
  preview: ClipPreview,
  { widthPx, height, fps, srcInFrame, durationInFrames, playbackRate }: {
    widthPx: number; height: number; fps: number;
    srcInFrame: number; durationInFrames: number; playbackRate: number;
  },
): string {
  const { peaks, peaksPerSecond } = preview;
  if (!peaks.length || widthPx <= 0) return '';
  const rate = playbackRate > 0 ? playbackRate : 1;
  const cols = Math.max(1, Math.min(2000, Math.floor(widthPx / 2)));
  const mid = height / 2;
  const perFrame = peaksPerSecond / fps; // How many peaks does one source frame correspond to?
  const startIdx = srcInFrame * perFrame;
  const spanIdx = durationInFrames * rate * perFrame;
  const out: string[] = [];
  for (let c = 0; c < cols; c += 1) {
    const from = startIdx + (c / cols) * spanIdx;
    const to = startIdx + ((c + 1) / cols) * spanIdx;
    let peak = 0;
    const lo = Math.max(0, Math.floor(from));
    const hi = Math.min(peaks.length - 1, Math.max(lo, Math.ceil(to) - 1));
    for (let i = lo; i <= hi; i += 1) if (peaks[i]! > peak) peak = peaks[i]!;
    const amp = Math.max(0.5, peak * (mid - 0.5));
    const x = ((c + 0.5) / cols) * widthPx;
    out.push(`M${x.toFixed(1)} ${(mid - amp).toFixed(1)}V${(mid + amp).toFixed(1)}`);
  }
  return out.join(' ');
}
