import { useEffect, useState } from 'react';

// Preview data for timeline clips (sonic peaks + video thumbnail frame bars). Server /api/waveform、
// /api/filmstrip is generated and cached (see server/plugins/media-preview.ts); this module only manages
// "Deduplication by src + in-process caching + subscription" - only one request is sent when the same material is cut into N segments.
// Waveforms and frame strips are generated by local ffmpeg, and the client is responsible for time mapping.

export interface ClipPreview {
  /** 0..1 amplitude envelope,per second peaksPerSecond a;No audio track is an empty array */
  peaks: number[];
  peaksPerSecond: number;
  /** The actual length of the source file(Not the trimmed duration of the clip) */
  durationMs: number;
  /** video frame strip URL(only video;Not ready/failed as null) */
  stripUrl: string | null;
}

type Entry = { value: ClipPreview | null; promise: Promise<void> | null; listeners: Set<() => void> };

const entries = new Map<string, Entry>();

/** Only local assets can be previewed(blob:/remote URL The server cannot reach) */
export function isPreviewable(src: string | undefined): src is string {
  return !!src && src.startsWith('/media/uploads/');
}

function entryFor(key: string): Entry {
  let e = entries.get(key);
  if (!e) {
    e = { value: null, promise: null, listeners: new Set() };
    entries.set(key, e);
  }
  return e;
}

async function load(src: string, wantStrip: boolean, e: Entry): Promise<void> {
  const q = `src=${encodeURIComponent(src)}`;
  const wave = await fetch(`/api/waveform?${q}`)
    .then((r) => (r.ok ? r.json() as Promise<{ peaks?: number[]; peaksPerSecond?: number; durationMs?: number }> : null))
    .catch(() => null);
  // The frame bar only checks the availability once: if successful, the URL is handed over to the CSS background (the browser caches the bytes itself)
  const stripUrl = wantStrip
    ? await fetch(`/api/filmstrip?${q}`).then((r) => (r.ok ? `/api/filmstrip?${q}` : null)).catch(() => null)
    : null;
  e.value = {
    peaks: wave?.peaks ?? [],
    peaksPerSecond: wave?.peaksPerSecond ?? 100,
    durationMs: wave?.durationMs ?? 0,
    stripUrl,
  };
  for (const fn of e.listeners) fn();
}

/**
 * Fragment preview data. same src Multiple fragments share one request and one result.
 * kind Decide whether to use frame strips(video Just want);Non-native materials are returned directly null。
 */
export function useClipPreview(src: string | undefined, kind: string): ClipPreview | null {
  const key = isPreviewable(src) ? src : '';
  const wantStrip = kind === 'video';
  const [, bump] = useState(0);

  useEffect(() => {
    if (!key) return;
    const e = entryFor(key);
    const onChange = () => bump((n) => n + 1);
    e.listeners.add(onChange);
    if (!e.value && !e.promise) {
      e.promise = load(key, wantStrip, e).finally(() => { e.promise = null; });
    }
    return () => { e.listeners.delete(onChange); };
  }, [key, wantStrip]);

  return key ? entryFor(key).value : null;
}

/**
 * Geometry mapping within fragments:
 * Clip left edge aligned to source frame srcIn,Advance each timeline pixel playbackRate/px source frame.
 * Full frame coverage [0, Source duration),Therefore CSS Background horizontal size = Source frames × px / rate,
 * Lateral displacement = -srcIn × px / rate。
 */
export function filmstripBackground(
  preview: ClipPreview,
  { px, fps, srcInFrame, playbackRate }: { px: number; fps: number; srcInFrame: number; playbackRate: number },
): { backgroundImage: string; backgroundSize: string; backgroundPositionX: string } | null {
  if (!preview.stripUrl || !preview.durationMs) return null;
  const rate = playbackRate > 0 ? playbackRate : 1;
  const srcFrames = (preview.durationMs / 1000) * fps;
  const fullW = (srcFrames * px) / rate;
  if (!(fullW > 0)) return null;
  return {
    backgroundImage: `url(${preview.stripUrl})`,
    backgroundSize: `${fullW.toFixed(1)}px 100%`,
    backgroundPositionX: `${(-(srcInFrame * px) / rate).toFixed(1)}px`,
  };
}

/**
 * The sonic path within the clip's visible window(same mapping as frame strip). Return SVG path;If there is no peak, an empty string is returned.
 * The ordinate is height/2 axially symmetrical,x Get the maximum peak value covered by the column by pixel column by column(Avoid sampling flicker)。
 */
export function peaksPath(
  preview: ClipPreview,
  { widthPx, height, fps, srcInFrame, durationInFrames, playbackRate }: {
    widthPx: number; height: number; fps: number;
    srcInFrame: number; durationInFrames: number; playbackRate: number;
  },
): string {
  const { peaks, peaksPerSecond } = preview;
  if (!peaks.length || widthPx <= 0) return '';
  const rate = playbackRate > 0 ? playbackRate : 1;
  const cols = Math.max(1, Math.min(2000, Math.floor(widthPx / 2)));
  const mid = height / 2;
  const perFrame = peaksPerSecond / fps; // How many peaks does one source frame correspond to?
  const startIdx = srcInFrame * perFrame;
  const spanIdx = durationInFrames * rate * perFrame;
  const out: string[] = [];
  for (let c = 0; c < cols; c += 1) {
    const from = startIdx + (c / cols) * spanIdx;
    const to = startIdx + ((c + 1) / cols) * spanIdx;
    let peak = 0;
    const lo = Math.max(0, Math.floor(from));
    const hi = Math.min(peaks.length - 1, Math.max(lo, Math.ceil(to) - 1));
    for (let i = lo; i <= hi; i += 1) if (peaks[i]! > peak) peak = peaks[i]!;
    const amp = Math.max(0.5, peak * (mid - 0.5));
    const x = ((c + 0.5) / cols) * widthPx;
    out.push(`M${x.toFixed(1)} ${(mid - amp).toFixed(1)}V${(mid + amp).toFixed(1)}`);
  }
  return out.join(' ');
}
