// Material pool MG card thumbnail: The motion-graphic material generated by the agent only has code and no preview image.
// (The resource library template card comes with a preview image, and there is no customized MG in the pool). Here is the code scene
// compileTemplate post-renders a mini Remotion Player - still in the middle frame (title animation
// There are words only in the middle frame), hover to play, and move back to the middle frame. If compilation fails, it will fall back to the star placeholder (consistent with the old look and feel).
import { useMemo, useRef } from 'react';
import { Player, type PlayerRef } from '@remotion/player';
import { compileTemplate } from '../template-host';
import type { MediaAsset } from '../editor/types';
import { Icon } from '../components/icons';

interface MgThumbProps {
  asset: MediaAsset;
  fps: number;
}

export function MgThumb({ asset, fps }: MgThumbProps) {
  const playerRef = useRef<PlayerRef | null>(null);
  const compiled = useMemo(() => {
    if (!asset.code) return null;
    try {
      return compileTemplate(asset.code);
    } catch {
      return null; // Bad code does not blow up the card, it falls back to take up space
    }
  }, [asset.code]);

  if (!compiled) {
    return <Icon name="sparkles" size={42} strokeWidth={2.2} />;
  }

  const dw = asset.width ?? 1920;
  const dh = asset.height ?? 1080;
  const duration = Math.max(1, asset.durationInFrames || 60);
  const mid = Math.floor(duration / 2);
  const Template = compiled;

  return (
    <div
      style={{ width: '100%', height: '100%' }}
      onMouseEnter={() => playerRef.current?.play()}
      onMouseLeave={() => { playerRef.current?.pause(); playerRef.current?.seekTo(mid); }}
    >
      <Player
        ref={playerRef}
        component={Template}
        inputProps={{ item: { props: asset.props ?? {}, width: dw, height: dh } }}
        durationInFrames={duration}
        compositionWidth={dw}
        compositionHeight={dh}
        fps={fps}
        initialFrame={mid}
        loop
        controls={false}
        clickToPlay={false}
        // Click the button to pass through to the card (add to the timeline); the hover event is received by the outer div
        style={{ width: '100%', height: '100%', pointerEvents: 'none' }}
        acknowledgeRemotionLicense
      />
    </div>
  );
}
